name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.11.0+2

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android_camerax
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

publish_to: 'none'

dependencies:
  camera_android_camerax:
    git:
      url: git@github.com:marvin-kolja/packages.git
      path: packages/camera/camera_android_camerax
      ref: '45603f6e4ced6a8dfa2a35c26a99b3a95f19054c'
  camera_avfoundation:
    git:
      url: git@github.com:marvin-kolja/packages.git
      path: packages/camera/camera_avfoundation
      ref: '45603f6e4ced6a8dfa2a35c26a99b3a95f19054c'
  camera_platform_interface:
    git:
      url: git@github.com:marvin-kolja/packages.git
      path: packages/camera/camera_platform_interface
      ref: '223d4feed4ecd1bb83430095c02dae6451eee4de'
  camera_web:
    git:
      url: git@github.com:marvin-kolja/packages.git
      path: packages/camera/camera_web
      ref: '45603f6e4ced6a8dfa2a35c26a99b3a95f19054c'
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.7

topics:
  - camera
