name: camera_android_camerax
description: Android implementation of the camera plugin using the CameraX library.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.6.10

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camerax
        pluginClass: CameraAndroidCameraxPlugin
        dartPluginClass: AndroidCameraCameraX

publish_to: 'none'

dependencies:
  async: ^2.5.0
  camera_platform_interface:
    git:
      url: git@github.com:marvin-kolja/packages.git
      path: packages/camera/camera_platform_interface
      ref: 'e98eb9df2ba2822ac16ae6265454129d80a65f64'
  flutter:
    sdk: flutter
  meta: ^1.7.0
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^9.1.0

topics:
  - camera
