name: camera_avfoundation
description: iOS implementation of the camera plugin.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_avfoundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.9.17+3

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

flutter:
  plugin:
    implements: camera
    platforms:
      ios:
        pluginClass: CameraPlugin
        dartPluginClass: AVFoundationCamera

publish_to: 'none'

dependencies:
  camera_platform_interface:
    git:
      url: git@github.com:marvin-kolja/packages.git
      path: packages/camera/camera_platform_interface
      ref: 'e98eb9df2ba2822ac16ae6265454129d80a65f64'
  flutter:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^18.0.0

topics:
  - camera
